FROM golang:1.7-alpine

COPY . /go/src/github.com/vdemeester/break-all-the-thing/lock-my-daemon
WORKDIR /go/src/github.com/vdemeester/break-all-the-thing/lock-my-daemon

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
    gcc libc-dev \
    && go install --ldflags '-extldflags "-static"' \
    && apk del .build-deps

CMD ["/go/bin/lock-my-daemon"]