version: "3.0"

services:
  foo:
    image: busybox
    command: top
    networks:
      - baz
  bar:
    image: busybox
    command: top
    networks:
      - baz
      - bat
  expose:
    image: nginx
    ports:
      - 80:80
    networks:
      - baz

networks:
  baz:
  bat:
